In [98]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [99]:
data = pd.read_csv('datasets.csv')

In [100]:
data

Unnamed: 0  city  area  rooms  bathroom  parking spaces floor  \
0              0     1   240      3         3               4     -   
1              1     0    64      2         1               1    10   
2              2     1   443      5         5               4     3   
3              3     1    73      2         2               1    12   
4              4     1    19      1         1               0     -   
...          ...   ...   ...    ...       ...             ...   ...   
6075        6075     1    50      2         1               1     2   
6076        6076     1    84      2         2               1    16   
6077        6077     0    48      1         1               0    13   
6078        6078     1   160      3         2               2     -   
6079        6079     1    60      2         1               1     4   

         animal      furniture      hoa rent amount property tax  \
0         acept      furnished      R$0     R$8,000      R$1,000   
1         acept  not furnished    R$540       R$820        R$122   
2         acept      furnished  R$4,172     R$7,000      R$1,417   
3         acept  not furnished    R$700     R$1,250        R$150   
4     not acept  not furnished      R$0     R$1,200         R$41   
...         ...            ...      ...         ...          ...   
6075      acept  not furnished    R$420     R$1,150          R$0   
6076  not acept      furnished    R$768     R$2,900         R$63   
6077      acept  not furnished    R$250       R$950         R$42   
6078  not acept  not furnished      R$0     R$3,500        R$250   
6079      acept      furnished    R$489     R$1,900          R$0   

     fire insurance     total  
0             R$121   R$9,121  
1              R$11   R$1,493  
2              R$89  R$12,680  
3              R$16   R$2,116  
4              R$16   R$1,257  
...             ...       ...  
6075           R$15   R$1,585  
6076           R$37   R$3,768  
6077           R$13   R$1,255  
6078           R$53   R$3,803  
6079           R$25   R$2,414  

[6080 rows x 14 columns]

In [101]:
data.drop(['Unnamed: 0'], axis=1, inplace=True)

In [102]:
data.head()

city  area  rooms  bathroom  parking spaces floor     animal  \
0     1   240      3         3               4     -      acept   
1     0    64      2         1               1    10      acept   
2     1   443      5         5               4     3      acept   
3     1    73      2         2               1    12      acept   
4     1    19      1         1               0     -  not acept   

       furniture      hoa rent amount property tax fire insurance     total  
0      furnished      R$0     R$8,000      R$1,000          R$121   R$9,121  
1  not furnished    R$540       R$820        R$122           R$11   R$1,493  
2      furnished  R$4,172     R$7,000      R$1,417           R$89  R$12,680  
3  not furnished    R$700     R$1,250        R$150           R$16   R$2,116  
4  not furnished      R$0     R$1,200         R$41           R$16   R$1,257

In [103]:
data.tail()

city  area  rooms  bathroom  parking spaces floor     animal  \
6075     1    50      2         1               1     2      acept   
6076     1    84      2         2               1    16  not acept   
6077     0    48      1         1               0    13      acept   
6078     1   160      3         2               2     -  not acept   
6079     1    60      2         1               1     4      acept   

          furniture    hoa rent amount property tax fire insurance    total  
6075  not furnished  R$420     R$1,150          R$0           R$15  R$1,585  
6076      furnished  R$768     R$2,900         R$63           R$37  R$3,768  
6077  not furnished  R$250       R$950         R$42           R$13  R$1,255  
6078  not furnished    R$0     R$3,500        R$250           R$53  R$3,803  
6079      furnished  R$489     R$1,900          R$0           R$25  R$2,414

In [104]:
data.shape

(6080, 13)

In [105]:
data.isnull().any()

city              False
area              False
rooms             False
bathroom          False
parking spaces    False
floor             False
animal            False
furniture         False
hoa               False
rent amount       False
property tax      False
fire insurance    False
total             False
dtype: bool

In [106]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6080 entries, 0 to 6079
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   city            6080 non-null   int64 
 1   area            6080 non-null   int64 
 2   rooms           6080 non-null   int64 
 3   bathroom        6080 non-null   int64 
 4   parking spaces  6080 non-null   int64 
 5   floor           6080 non-null   object
 6   animal          6080 non-null   object
 7   furniture       6080 non-null   object
 8   hoa             6080 non-null   object
 9   rent amount     6080 non-null   object
 10  property tax    6080 non-null   object
 11  fire insurance  6080 non-null   object
 12  total           6080 non-null   object
dtypes: int64(5), object(8)
memory usage: 617.6+ KB


In [107]:
data.describe()

city          area        rooms     bathroom  parking spaces
count  6080.000000   6080.000000  6080.000000  6080.000000     6080.000000
mean      0.863322    151.143914     2.492599     2.341612        1.756250
std       0.343535    375.559485     1.129665     1.438860        1.611909
min       0.000000     10.000000     1.000000     1.000000        0.000000
25%       1.000000     58.000000     2.000000     1.000000        1.000000
50%       1.000000    100.000000     3.000000     2.000000        1.000000
75%       1.000000    200.000000     3.000000     3.000000        2.000000
max       1.000000  24606.000000    10.000000    10.000000       12.000000

### Data Cleaning

In [108]:
data['floor'].value_counts()

-     1555
1      573
3      401
2      379
4      319
5      314
6      306
8      291
7      287
9      224
10     213
11     193
12     179
13     143
14     141
15     107
16      89
17      73
18      69
19      47
20      36
21      30
23      26
25      23
22      21
24      11
27       7
28       6
26       6
29       4
32       1
99       1
51       1
68       1
31       1
85       1
35       1
Name: floor, dtype: int64

In [110]:
#remove the '-'
import numpy as np
data['floor']= data['floor'].replace('-',np.nan)

In [111]:
data['floor'].value_counts()

1     573
3     401
2     379
4     319
5     314
6     306
8     291
7     287
9     224
10    213
11    193
12    179
13    143
14    141
15    107
16     89
17     73
18     69
19     47
20     36
21     30
23     26
25     23
22     21
24     11
27      7
28      6
26      6
29      4
31      1
32      1
99      1
51      1
85      1
68      1
35      1
Name: floor, dtype: int64

In [113]:
data['floor']=pd.to_numeric(data['floor'])

In [114]:
data['floor'].fillna(data['floor'].mean(), inplace=True)

In [115]:
data['floor'].value_counts()

7.621436     1555
1.000000      573
3.000000      401
2.000000      379
4.000000      319
5.000000      314
6.000000      306
8.000000      291
7.000000      287
9.000000      224
10.000000     213
11.000000     193
12.000000     179
13.000000     143
14.000000     141
15.000000     107
16.000000      89
17.000000      73
18.000000      69
19.000000      47
20.000000      36
21.000000      30
23.000000      26
25.000000      23
22.000000      21
24.000000      11
27.000000       7
28.000000       6
26.000000       6
29.000000       4
68.000000       1
31.000000       1
51.000000       1
99.000000       1
32.000000       1
85.000000       1
35.000000       1
Name: floor, dtype: int64

### Categorical Variables

In [82]:
data['city'].unique()

array([1, 0])

In [83]:
data['rooms'].unique()

array([ 3,  2,  5,  1,  4,  7,  6,  8, 10])

In [84]:
data['bathroom'].unique()

array([ 3,  1,  5,  2,  4,  6,  7, 10,  9,  8])

In [85]:
data['animal'].unique()

array(['acept', 'not acept'], dtype=object)

In [86]:
data['furniture'].unique()

array(['furnished', 'not furnished'], dtype=object)

In [87]:
data['parking spaces'].unique()

array([ 4,  1,  0,  5,  8,  2,  3,  6,  7, 12])

In [88]:
#data['hoa'].value_counts()

### Removing dollar

In [89]:
#remving dollar signs and other special characters
def dollar_delete(x):
    x = x[2:]
    r=''
    for i in x:
        if i.isdigit():
            r+=i
    return r

In [ ]:
#converting object type to integer

In [90]:
data['hoa']=pd.to_numeric(data['hoa'].apply(dollar_delete))

In [91]:
data['rent amount']=pd.to_numeric(data['rent amount'].apply(dollar_delete))

In [92]:
data['property tax']=pd.to_numeric(data['property tax'].apply(dollar_delete))

In [93]:
data['fire insurance']=pd.to_numeric(data['fire insurance'].apply(dollar_delete))

In [94]:
data['total']=pd.to_numeric(data['total'].apply(dollar_delete))

In [95]:
data.head()

city  area  rooms  bathroom  parking spaces floor     animal  \
0     1   240      3         3               4     0      acept   
1     0    64      2         1               1    10      acept   
2     1   443      5         5               4     3      acept   
3     1    73      2         2               1    12      acept   
4     1    19      1         1               0     0  not acept   

       furniture     hoa  rent amount  property tax  fire insurance  total  
0      furnished     0.0         8000        1000.0             121   9121  
1  not furnished   540.0          820         122.0              11   1493  
2      furnished  4172.0         7000        1417.0              89  12680  
3  not furnished   700.0         1250         150.0              16   2116  
4  not furnished     0.0         1200          41.0              16   1257

In [96]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6080 entries, 0 to 6079
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   city            6080 non-null   int64  
 1   area            6080 non-null   int64  
 2   rooms           6080 non-null   int64  
 3   bathroom        6080 non-null   int64  
 4   parking spaces  6080 non-null   int64  
 5   floor           6080 non-null   object 
 6   animal          6080 non-null   object 
 7   furniture       6080 non-null   object 
 8   hoa             5878 non-null   float64
 9   rent amount     6080 non-null   int64  
 10  property tax    6053 non-null   float64
 11  fire insurance  6080 non-null   int64  
 12  total           6080 non-null   int64  
dtypes: float64(2), int64(8), object(3)
memory usage: 617.6+ KB
